language: cpp

matrix:
  include:

    - name: "Ubuntu 16.04 LTS (Xenial Xerus) GCC 5" 
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libpcap-dev
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

    - name: "Ubuntu 16.04 LTS (Xenial Xerus) GCC 6" 
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libpcap-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - name: "Ubuntu 16.04 LTS (Xenial Xerus) GCC 7" 
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libpcap-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - name: "Ubuntu 16.04 LTS (Xenial Xerus) GCC 8" 
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libpcap-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - name: "Ubuntu 16.04 LTS (Xenial Xerus) GCC 9" 
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libpcap-dev
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) GCC 7" 
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libpcap-dev
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) GCC 8" 
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libpcap-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) Clang 4" 
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-4.0
          packages:
            - clang-4.0
            - libpcap-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) Clang 5" 
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-5.0
          packages:
            - clang-5.0
            - libpcap-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) Clang 6" 
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-6.0
          packages:
            - clang-6.0
            - libpcap-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) Clang 7" 
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-7
          packages:
            - clang-7
            - libpcap-dev
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) Clang 8" 
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-8
          packages:
            - clang-8
            - libpcap-dev
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_CXX_FLAGS="-Werror" ..

script: make && ctest
